# GNU Make solution makefile autogenerated by GENie
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := Project

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

Project: 
	@echo "==== Building Project ($(config)) ===="
	@${MAKE} --no-print-directory -C Project -f Makefile

clean:
	@${MAKE} --no-print-directory -C Project -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo "   debug64"
	@echo "   release64"
	@echo "   debug32"
	@echo "   release32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Project"
	@echo ""
	@echo "For more information, see https://github.com/bkaradzic/genie"
